// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppMerck.AccesoDatos.DataAccess;

#nullable disable

namespace WebAppMerck.AccesoDatos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("NombreClinica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Clinicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Viamonte 1432",
                            Latitud = -34.6007441,
                            Longitud = -58.387174100000003,
                            NombreClinica = "CEGYR Medicina Reproductiva",
                            NombreProvincia = "Capital Federal",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Humboldt 2263",
                            Latitud = -34.5806714,
                            Longitud = -58.4302438,
                            NombreClinica = "CER",
                            NombreProvincia = "Catamarca",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Av.Forest 1166",
                            Latitud = -34.578822199999998,
                            Longitud = -58.460096700000001,
                            NombreClinica = "Centro de Investigaciones en Medicina Reproductiva",
                            NombreProvincia = "Chaco",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Alvear 514",
                            Latitud = -34.7197709,
                            Longitud = -58.256260400000002,
                            NombreClinica = "Centro Gens",
                            NombreProvincia = "Chubut",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 5,
                            Direccion = "Marcelo T. de Alvear 2084",
                            Latitud = -34.597464299999999,
                            Longitud = -58.3971746,
                            NombreClinica = "Halitus Instituto Médico",
                            NombreProvincia = "Capital Federal",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 6,
                            Direccion = "Bulnes 1104",
                            Latitud = -34.598300000000002,
                            Longitud = -58.417900000000003,
                            NombreClinica = "Maternity Bank",
                            NombreProvincia = "Capital Federal",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 7,
                            Direccion = "Av. del Libertador 5962",
                            Latitud = -34.557099999999998,
                            Longitud = -58.447600000000001,
                            NombreClinica = "WeFIV",
                            NombreProvincia = "Capital Federal",
                            ProvinciaId = 3
                        });
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clinica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaYhora")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consultas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clinica = "CEGYR Medicina Reproductiva",
                            FechaYhora = new DateTime(2024, 1, 8, 7, 21, 22, 106, DateTimeKind.Local).AddTicks(7171),
                            MotivoConsulta = "Edad y Reserva Ovarica",
                            Url = "https://ejemplo.com/"
                        },
                        new
                        {
                            Id = 2,
                            Clinica = "Centro de Investigaciones en Medicina Reproductiva",
                            FechaYhora = new DateTime(2024, 1, 8, 7, 21, 22, 106, DateTimeKind.Local).AddTicks(7228),
                            MotivoConsulta = "Evaluación de Reserva Ovárica",
                            Url = "https://ejemplo2.com/"
                        });
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("NombreLocalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdProvincia = 1,
                            NombreLocalidad = "25 de Mayo"
                        },
                        new
                        {
                            Id = 2,
                            IdProvincia = 1,
                            NombreLocalidad = "3 de febrero"
                        },
                        new
                        {
                            Id = 3,
                            IdProvincia = 1,
                            NombreLocalidad = "A. Alsina"
                        },
                        new
                        {
                            Id = 4,
                            IdProvincia = 1,
                            NombreLocalidad = "A. Gonzáles Cháves"
                        },
                        new
                        {
                            Id = 5,
                            IdProvincia = 1,
                            NombreLocalidad = "Aguas Verdes"
                        },
                        new
                        {
                            Id = 6,
                            IdProvincia = 1,
                            NombreLocalidad = "Alberti"
                        },
                        new
                        {
                            Id = 7,
                            IdProvincia = 1,
                            NombreLocalidad = "Arrecifes"
                        },
                        new
                        {
                            Id = 8,
                            IdProvincia = 1,
                            NombreLocalidad = "Ayacucho"
                        },
                        new
                        {
                            Id = 9,
                            IdProvincia = 1,
                            NombreLocalidad = "Azul"
                        },
                        new
                        {
                            Id = 10,
                            IdProvincia = 1,
                            NombreLocalidad = "Bahía Blanca"
                        },
                        new
                        {
                            Id = 11,
                            IdProvincia = 1,
                            NombreLocalidad = "Balcarce"
                        },
                        new
                        {
                            Id = 12,
                            IdProvincia = 1,
                            NombreLocalidad = "Baradero"
                        },
                        new
                        {
                            Id = 13,
                            IdProvincia = 1,
                            NombreLocalidad = "Benito Juárez"
                        },
                        new
                        {
                            Id = 14,
                            IdProvincia = 1,
                            NombreLocalidad = "Berisso"
                        },
                        new
                        {
                            Id = 15,
                            IdProvincia = 1,
                            NombreLocalidad = "Bolívar"
                        },
                        new
                        {
                            Id = 16,
                            IdProvincia = 1,
                            NombreLocalidad = "Bragado"
                        },
                        new
                        {
                            Id = 17,
                            IdProvincia = 1,
                            NombreLocalidad = "Brandsen"
                        },
                        new
                        {
                            Id = 18,
                            IdProvincia = 1,
                            NombreLocalidad = "Campana"
                        },
                        new
                        {
                            Id = 19,
                            IdProvincia = 1,
                            NombreLocalidad = "Cañuelas"
                        },
                        new
                        {
                            Id = 20,
                            IdProvincia = 1,
                            NombreLocalidad = "Capilla del Señor"
                        },
                        new
                        {
                            Id = 21,
                            IdProvincia = 1,
                            NombreLocalidad = "Capitán Sarmiento"
                        },
                        new
                        {
                            Id = 22,
                            IdProvincia = 1,
                            NombreLocalidad = "Carapachay"
                        },
                        new
                        {
                            Id = 23,
                            IdProvincia = 1,
                            NombreLocalidad = "Carhue"
                        },
                        new
                        {
                            Id = 24,
                            IdProvincia = 1,
                            NombreLocalidad = "Cariló"
                        },
                        new
                        {
                            Id = 25,
                            IdProvincia = 1,
                            NombreLocalidad = "Carlos Casares"
                        },
                        new
                        {
                            Id = 26,
                            IdProvincia = 1,
                            NombreLocalidad = "Carlos Tejedor"
                        },
                        new
                        {
                            Id = 27,
                            IdProvincia = 1,
                            NombreLocalidad = "Carmen de Areco"
                        },
                        new
                        {
                            Id = 28,
                            IdProvincia = 1,
                            NombreLocalidad = "Carmen de Patagones"
                        },
                        new
                        {
                            Id = 29,
                            IdProvincia = 1,
                            NombreLocalidad = "Castelli"
                        },
                        new
                        {
                            Id = 30,
                            IdProvincia = 1,
                            NombreLocalidad = "Chacabuco"
                        },
                        new
                        {
                            Id = 31,
                            IdProvincia = 1,
                            NombreLocalidad = "Chascomús"
                        },
                        new
                        {
                            Id = 32,
                            IdProvincia = 1,
                            NombreLocalidad = "Chivilcoy"
                        },
                        new
                        {
                            Id = 33,
                            IdProvincia = 1,
                            NombreLocalidad = "Colón"
                        },
                        new
                        {
                            Id = 34,
                            IdProvincia = 1,
                            NombreLocalidad = "Coronel Dorrego"
                        },
                        new
                        {
                            Id = 35,
                            IdProvincia = 1,
                            NombreLocalidad = "Coronel Pringles"
                        },
                        new
                        {
                            Id = 36,
                            IdProvincia = 1,
                            NombreLocalidad = "Coronel Rosales"
                        },
                        new
                        {
                            Id = 37,
                            IdProvincia = 1,
                            NombreLocalidad = "Coronel Suarez"
                        },
                        new
                        {
                            Id = 38,
                            IdProvincia = 1,
                            NombreLocalidad = "Costa Azul"
                        },
                        new
                        {
                            Id = 39,
                            IdProvincia = 1,
                            NombreLocalidad = "Costa Chica"
                        },
                        new
                        {
                            Id = 40,
                            IdProvincia = 1,
                            NombreLocalidad = "Costa del Este"
                        },
                        new
                        {
                            Id = 41,
                            IdProvincia = 1,
                            NombreLocalidad = "Costa Esmeralda"
                        },
                        new
                        {
                            Id = 42,
                            IdProvincia = 1,
                            NombreLocalidad = "Daireaux"
                        },
                        new
                        {
                            Id = 43,
                            IdProvincia = 1,
                            NombreLocalidad = "Darregueira"
                        },
                        new
                        {
                            Id = 44,
                            IdProvincia = 1,
                            NombreLocalidad = "Del Viso"
                        },
                        new
                        {
                            Id = 45,
                            IdProvincia = 1,
                            NombreLocalidad = "Dolores"
                        },
                        new
                        {
                            Id = 46,
                            IdProvincia = 1,
                            NombreLocalidad = "Don Torcuato"
                        },
                        new
                        {
                            Id = 47,
                            IdProvincia = 1,
                            NombreLocalidad = "Ensenada"
                        },
                        new
                        {
                            Id = 48,
                            IdProvincia = 1,
                            NombreLocalidad = "Escobar"
                        },
                        new
                        {
                            Id = 49,
                            IdProvincia = 1,
                            NombreLocalidad = "Exaltación de la Cruz"
                        },
                        new
                        {
                            Id = 50,
                            IdProvincia = 1,
                            NombreLocalidad = "Florentino Ameghino"
                        },
                        new
                        {
                            Id = 282,
                            IdProvincia = 3,
                            NombreLocalidad = "Agronomía"
                        },
                        new
                        {
                            Id = 283,
                            IdProvincia = 3,
                            NombreLocalidad = "Almagro"
                        },
                        new
                        {
                            Id = 284,
                            IdProvincia = 3,
                            NombreLocalidad = "Balvanera"
                        },
                        new
                        {
                            Id = 285,
                            IdProvincia = 3,
                            NombreLocalidad = "Barracas"
                        },
                        new
                        {
                            Id = 286,
                            IdProvincia = 3,
                            NombreLocalidad = "Belgrano"
                        },
                        new
                        {
                            Id = 287,
                            IdProvincia = 3,
                            NombreLocalidad = "Boca"
                        },
                        new
                        {
                            Id = 288,
                            IdProvincia = 3,
                            NombreLocalidad = "Boedo"
                        },
                        new
                        {
                            Id = 289,
                            IdProvincia = 3,
                            NombreLocalidad = "Caballito"
                        },
                        new
                        {
                            Id = 290,
                            IdProvincia = 3,
                            NombreLocalidad = "Chacarita"
                        },
                        new
                        {
                            Id = 291,
                            IdProvincia = 3,
                            NombreLocalidad = "Coghlan"
                        },
                        new
                        {
                            Id = 292,
                            IdProvincia = 3,
                            NombreLocalidad = "Colegiales"
                        },
                        new
                        {
                            Id = 293,
                            IdProvincia = 3,
                            NombreLocalidad = "Constitución"
                        },
                        new
                        {
                            Id = 294,
                            IdProvincia = 3,
                            NombreLocalidad = "Flores"
                        },
                        new
                        {
                            Id = 295,
                            IdProvincia = 3,
                            NombreLocalidad = "Floresta"
                        },
                        new
                        {
                            Id = 296,
                            IdProvincia = 3,
                            NombreLocalidad = "La Paternal"
                        },
                        new
                        {
                            Id = 297,
                            IdProvincia = 3,
                            NombreLocalidad = "Liniers"
                        },
                        new
                        {
                            Id = 298,
                            IdProvincia = 3,
                            NombreLocalidad = "Mataderos"
                        },
                        new
                        {
                            Id = 299,
                            IdProvincia = 3,
                            NombreLocalidad = "Monserrat"
                        },
                        new
                        {
                            Id = 300,
                            IdProvincia = 3,
                            NombreLocalidad = "Monte Castro"
                        },
                        new
                        {
                            Id = 301,
                            IdProvincia = 3,
                            NombreLocalidad = "Nueva Pompeya"
                        },
                        new
                        {
                            Id = 302,
                            IdProvincia = 3,
                            NombreLocalidad = "Núñez"
                        },
                        new
                        {
                            Id = 303,
                            IdProvincia = 3,
                            NombreLocalidad = "Palermo"
                        },
                        new
                        {
                            Id = 304,
                            IdProvincia = 3,
                            NombreLocalidad = "Parque Avellaneda"
                        },
                        new
                        {
                            Id = 305,
                            IdProvincia = 3,
                            NombreLocalidad = "Parque Chacabuco"
                        },
                        new
                        {
                            Id = 306,
                            IdProvincia = 3,
                            NombreLocalidad = "Parque Chas"
                        },
                        new
                        {
                            Id = 307,
                            IdProvincia = 3,
                            NombreLocalidad = "Parque Patricios"
                        },
                        new
                        {
                            Id = 308,
                            IdProvincia = 3,
                            NombreLocalidad = "Puerto Madero"
                        },
                        new
                        {
                            Id = 309,
                            IdProvincia = 3,
                            NombreLocalidad = "Recoleta"
                        },
                        new
                        {
                            Id = 310,
                            IdProvincia = 3,
                            NombreLocalidad = "Retiro"
                        },
                        new
                        {
                            Id = 311,
                            IdProvincia = 3,
                            NombreLocalidad = "Saavedra"
                        },
                        new
                        {
                            Id = 312,
                            IdProvincia = 3,
                            NombreLocalidad = "San Cristóbal"
                        },
                        new
                        {
                            Id = 313,
                            IdProvincia = 3,
                            NombreLocalidad = "San Nicolás"
                        },
                        new
                        {
                            Id = 314,
                            IdProvincia = 3,
                            NombreLocalidad = "San Telmo"
                        },
                        new
                        {
                            Id = 315,
                            IdProvincia = 3,
                            NombreLocalidad = "Vélez Sársfield"
                        },
                        new
                        {
                            Id = 316,
                            IdProvincia = 3,
                            NombreLocalidad = "Versalles"
                        },
                        new
                        {
                            Id = 317,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Crespo"
                        },
                        new
                        {
                            Id = 318,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa del Parque"
                        },
                        new
                        {
                            Id = 319,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Devoto"
                        },
                        new
                        {
                            Id = 320,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Gral. Mitre"
                        },
                        new
                        {
                            Id = 321,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Lugano"
                        },
                        new
                        {
                            Id = 322,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Luro"
                        },
                        new
                        {
                            Id = 323,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Ortúzar"
                        },
                        new
                        {
                            Id = 324,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Pueyrredón"
                        },
                        new
                        {
                            Id = 325,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Real"
                        },
                        new
                        {
                            Id = 326,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Riachuelo"
                        },
                        new
                        {
                            Id = 327,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Santa Rita"
                        },
                        new
                        {
                            Id = 328,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Soldati"
                        },
                        new
                        {
                            Id = 329,
                            IdProvincia = 3,
                            NombreLocalidad = "Villa Urquiza"
                        },
                        new
                        {
                            Id = 330,
                            IdProvincia = 4,
                            NombreLocalidad = "Aconquija"
                        },
                        new
                        {
                            Id = 331,
                            IdProvincia = 4,
                            NombreLocalidad = "Ancasti"
                        },
                        new
                        {
                            Id = 332,
                            IdProvincia = 4,
                            NombreLocalidad = "Andalgalá"
                        },
                        new
                        {
                            Id = 333,
                            IdProvincia = 4,
                            NombreLocalidad = "Antofagasta"
                        },
                        new
                        {
                            Id = 334,
                            IdProvincia = 4,
                            NombreLocalidad = "Belén"
                        },
                        new
                        {
                            Id = 335,
                            IdProvincia = 4,
                            NombreLocalidad = "Capayán"
                        },
                        new
                        {
                            Id = 336,
                            IdProvincia = 4,
                            NombreLocalidad = "Capital"
                        },
                        new
                        {
                            Id = 337,
                            IdProvincia = 4,
                            NombreLocalidad = "4"
                        },
                        new
                        {
                            Id = 338,
                            IdProvincia = 4,
                            NombreLocalidad = "Corral Quemado"
                        },
                        new
                        {
                            Id = 339,
                            IdProvincia = 4,
                            NombreLocalidad = "El Alto"
                        },
                        new
                        {
                            Id = 340,
                            IdProvincia = 4,
                            NombreLocalidad = "El Rodeo"
                        },
                        new
                        {
                            Id = 341,
                            IdProvincia = 4,
                            NombreLocalidad = "F.Mamerto Esquiú"
                        },
                        new
                        {
                            Id = 342,
                            IdProvincia = 4,
                            NombreLocalidad = "Fiambalá"
                        },
                        new
                        {
                            Id = 343,
                            IdProvincia = 4,
                            NombreLocalidad = "Hualfín"
                        },
                        new
                        {
                            Id = 344,
                            IdProvincia = 4,
                            NombreLocalidad = "Huillapima"
                        },
                        new
                        {
                            Id = 345,
                            IdProvincia = 4,
                            NombreLocalidad = "Icaño"
                        },
                        new
                        {
                            Id = 346,
                            IdProvincia = 4,
                            NombreLocalidad = "La Puerta"
                        },
                        new
                        {
                            Id = 347,
                            IdProvincia = 4,
                            NombreLocalidad = "Las Juntas"
                        },
                        new
                        {
                            Id = 348,
                            IdProvincia = 4,
                            NombreLocalidad = "Londres"
                        },
                        new
                        {
                            Id = 381,
                            IdProvincia = 5,
                            NombreLocalidad = "Col. Elisa"
                        },
                        new
                        {
                            Id = 382,
                            IdProvincia = 5,
                            NombreLocalidad = "Col. Popular"
                        },
                        new
                        {
                            Id = 383,
                            IdProvincia = 5,
                            NombreLocalidad = "Colonias Unidas"
                        },
                        new
                        {
                            Id = 384,
                            IdProvincia = 5,
                            NombreLocalidad = "Concepción"
                        },
                        new
                        {
                            Id = 385,
                            IdProvincia = 5,
                            NombreLocalidad = "Corzuela"
                        },
                        new
                        {
                            Id = 386,
                            IdProvincia = 5,
                            NombreLocalidad = "Cote Lai"
                        },
                        new
                        {
                            Id = 387,
                            IdProvincia = 5,
                            NombreLocalidad = "El Sauzalito"
                        },
                        new
                        {
                            Id = 388,
                            IdProvincia = 5,
                            NombreLocalidad = "Enrique Urien"
                        },
                        new
                        {
                            Id = 389,
                            IdProvincia = 5,
                            NombreLocalidad = "Fontana"
                        },
                        new
                        {
                            Id = 390,
                            IdProvincia = 5,
                            NombreLocalidad = "Fte. Esperanza"
                        },
                        new
                        {
                            Id = 391,
                            IdProvincia = 5,
                            NombreLocalidad = "Gancedo"
                        },
                        new
                        {
                            Id = 392,
                            IdProvincia = 5,
                            NombreLocalidad = "Gral. Capdevila"
                        },
                        new
                        {
                            Id = 393,
                            IdProvincia = 5,
                            NombreLocalidad = "Gral. Pinero"
                        },
                        new
                        {
                            Id = 394,
                            IdProvincia = 5,
                            NombreLocalidad = "Gral. San Martín"
                        },
                        new
                        {
                            Id = 395,
                            IdProvincia = 5,
                            NombreLocalidad = "Gral. Vedia"
                        },
                        new
                        {
                            Id = 396,
                            IdProvincia = 5,
                            NombreLocalidad = "Hermoso Campo"
                        },
                        new
                        {
                            Id = 397,
                            IdProvincia = 5,
                            NombreLocalidad = "I. del Cerrito"
                        },
                        new
                        {
                            Id = 398,
                            IdProvincia = 5,
                            NombreLocalidad = "J.J. Castelli"
                        },
                        new
                        {
                            Id = 399,
                            IdProvincia = 5,
                            NombreLocalidad = "La Clotilde"
                        },
                        new
                        {
                            Id = 400,
                            IdProvincia = 5,
                            NombreLocalidad = "La Eduvigis"
                        },
                        new
                        {
                            Id = 401,
                            IdProvincia = 5,
                            NombreLocalidad = "La Escondida"
                        },
                        new
                        {
                            Id = 402,
                            IdProvincia = 5,
                            NombreLocalidad = "La Leonesa"
                        },
                        new
                        {
                            Id = 403,
                            IdProvincia = 5,
                            NombreLocalidad = "La Tigra"
                        },
                        new
                        {
                            Id = 404,
                            IdProvincia = 5,
                            NombreLocalidad = "La Verde"
                        },
                        new
                        {
                            Id = 453,
                            IdProvincia = 6,
                            NombreLocalidad = "Dolavón"
                        },
                        new
                        {
                            Id = 454,
                            IdProvincia = 6,
                            NombreLocalidad = "Dr. R. Rojas"
                        },
                        new
                        {
                            Id = 455,
                            IdProvincia = 6,
                            NombreLocalidad = "El Hoyo"
                        },
                        new
                        {
                            Id = 456,
                            IdProvincia = 6,
                            NombreLocalidad = "El Maitén"
                        },
                        new
                        {
                            Id = 457,
                            IdProvincia = 6,
                            NombreLocalidad = "Epuyén"
                        },
                        new
                        {
                            Id = 458,
                            IdProvincia = 6,
                            NombreLocalidad = "Esquel"
                        },
                        new
                        {
                            Id = 459,
                            IdProvincia = 6,
                            NombreLocalidad = "Facundo"
                        },
                        new
                        {
                            Id = 460,
                            IdProvincia = 6,
                            NombreLocalidad = "Gaimán"
                        },
                        new
                        {
                            Id = 461,
                            IdProvincia = 6,
                            NombreLocalidad = "Gan Gan"
                        },
                        new
                        {
                            Id = 462,
                            IdProvincia = 6,
                            NombreLocalidad = "Gastre"
                        },
                        new
                        {
                            Id = 463,
                            IdProvincia = 6,
                            NombreLocalidad = "Gdor. Costa"
                        },
                        new
                        {
                            Id = 464,
                            IdProvincia = 6,
                            NombreLocalidad = "Gualjaina"
                        },
                        new
                        {
                            Id = 465,
                            IdProvincia = 6,
                            NombreLocalidad = "J. de San Martín"
                        },
                        new
                        {
                            Id = 466,
                            IdProvincia = 6,
                            NombreLocalidad = "Lago Blanco"
                        },
                        new
                        {
                            Id = 467,
                            IdProvincia = 6,
                            NombreLocalidad = "Lago Puelo"
                        },
                        new
                        {
                            Id = 468,
                            IdProvincia = 6,
                            NombreLocalidad = "Lagunita Salada"
                        },
                        new
                        {
                            Id = 469,
                            IdProvincia = 6,
                            NombreLocalidad = "Las Plumas"
                        },
                        new
                        {
                            Id = 470,
                            IdProvincia = 6,
                            NombreLocalidad = "Los Altares"
                        },
                        new
                        {
                            Id = 504,
                            IdProvincia = 7,
                            NombreLocalidad = "Arias"
                        },
                        new
                        {
                            Id = 505,
                            IdProvincia = 7,
                            NombreLocalidad = "Arroyito"
                        },
                        new
                        {
                            Id = 506,
                            IdProvincia = 7,
                            NombreLocalidad = "Arroyo Algodon"
                        },
                        new
                        {
                            Id = 507,
                            IdProvincia = 7,
                            NombreLocalidad = "Arroyo Cabral"
                        },
                        new
                        {
                            Id = 508,
                            IdProvincia = 7,
                            NombreLocalidad = "Arroyo Los Patos"
                        },
                        new
                        {
                            Id = 509,
                            IdProvincia = 7,
                            NombreLocalidad = "Assunta"
                        },
                        new
                        {
                            Id = 510,
                            IdProvincia = 7,
                            NombreLocalidad = "Atahona"
                        },
                        new
                        {
                            Id = 511,
                            IdProvincia = 7,
                            NombreLocalidad = "Ausonia"
                        },
                        new
                        {
                            Id = 512,
                            IdProvincia = 7,
                            NombreLocalidad = "Avellaneda"
                        },
                        new
                        {
                            Id = 513,
                            IdProvincia = 7,
                            NombreLocalidad = "Ballesteros"
                        },
                        new
                        {
                            Id = 514,
                            IdProvincia = 7,
                            NombreLocalidad = "Ballesteros Sud"
                        },
                        new
                        {
                            Id = 515,
                            IdProvincia = 7,
                            NombreLocalidad = "Balnearia"
                        },
                        new
                        {
                            Id = 516,
                            IdProvincia = 7,
                            NombreLocalidad = "Bañado de Soto"
                        },
                        new
                        {
                            Id = 517,
                            IdProvincia = 7,
                            NombreLocalidad = "Bell Ville"
                        },
                        new
                        {
                            Id = 518,
                            IdProvincia = 7,
                            NombreLocalidad = "Bengolea"
                        },
                        new
                        {
                            Id = 519,
                            IdProvincia = 7,
                            NombreLocalidad = "Benjamin Gould"
                        },
                        new
                        {
                            Id = 520,
                            IdProvincia = 7,
                            NombreLocalidad = "Berrotaran"
                        },
                        new
                        {
                            Id = 521,
                            IdProvincia = 7,
                            NombreLocalidad = "Bialet Masse"
                        },
                        new
                        {
                            Id = 522,
                            IdProvincia = 7,
                            NombreLocalidad = "Bouwer"
                        },
                        new
                        {
                            Id = 523,
                            IdProvincia = 7,
                            NombreLocalidad = "Brinkmann"
                        },
                        new
                        {
                            Id = 524,
                            IdProvincia = 7,
                            NombreLocalidad = "Buchardo"
                        },
                        new
                        {
                            Id = 525,
                            IdProvincia = 7,
                            NombreLocalidad = "Bulnes"
                        },
                        new
                        {
                            Id = 526,
                            IdProvincia = 7,
                            NombreLocalidad = "Cabalango"
                        },
                        new
                        {
                            Id = 527,
                            IdProvincia = 7,
                            NombreLocalidad = "Calamuchita"
                        },
                        new
                        {
                            Id = 963,
                            IdProvincia = 8,
                            NombreLocalidad = "Saladas"
                        },
                        new
                        {
                            Id = 964,
                            IdProvincia = 8,
                            NombreLocalidad = "San Antonio"
                        });
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreProvincia = "Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            NombreProvincia = "Buenos Aires-GBA"
                        },
                        new
                        {
                            Id = 3,
                            NombreProvincia = "Capital Federal"
                        },
                        new
                        {
                            Id = 4,
                            NombreProvincia = "Catamarca"
                        },
                        new
                        {
                            Id = 5,
                            NombreProvincia = "Chaco"
                        },
                        new
                        {
                            Id = 6,
                            NombreProvincia = "Chubut"
                        },
                        new
                        {
                            Id = 7,
                            NombreProvincia = "Córdoba"
                        },
                        new
                        {
                            Id = 8,
                            NombreProvincia = "Corrientes"
                        },
                        new
                        {
                            Id = 9,
                            NombreProvincia = "Entre Ríos"
                        },
                        new
                        {
                            Id = 10,
                            NombreProvincia = "Formosa"
                        },
                        new
                        {
                            Id = 11,
                            NombreProvincia = "Jujuy"
                        },
                        new
                        {
                            Id = 12,
                            NombreProvincia = "La Pampa"
                        },
                        new
                        {
                            Id = 13,
                            NombreProvincia = "La Rioja"
                        },
                        new
                        {
                            Id = 14,
                            NombreProvincia = "Mendoza"
                        },
                        new
                        {
                            Id = 15,
                            NombreProvincia = "Misiones"
                        },
                        new
                        {
                            Id = 16,
                            NombreProvincia = "Neuquén"
                        },
                        new
                        {
                            Id = 17,
                            NombreProvincia = "Río Negro"
                        },
                        new
                        {
                            Id = 18,
                            NombreProvincia = "Salta"
                        },
                        new
                        {
                            Id = 19,
                            NombreProvincia = "San Juan"
                        },
                        new
                        {
                            Id = 20,
                            NombreProvincia = "San Luis"
                        },
                        new
                        {
                            Id = 21,
                            NombreProvincia = "Santa Cruz"
                        },
                        new
                        {
                            Id = 22,
                            NombreProvincia = "Santa Fe"
                        },
                        new
                        {
                            Id = 23,
                            NombreProvincia = "Santiago del Estero"
                        },
                        new
                        {
                            Id = 24,
                            NombreProvincia = "Tierra del Fuego"
                        },
                        new
                        {
                            Id = 25,
                            NombreProvincia = "Tucumán"
                        });
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Clave = "admin",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Clave = "usuario",
                            Email = "usuario@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = true,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebAppMerck.Modelos.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebAppMerck.Modelos.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppMerck.Modelos.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebAppMerck.Modelos.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Clinica", b =>
                {
                    b.HasOne("WebAppMerck.Modelos.Models.Entities.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Localidad", b =>
                {
                    b.HasOne("WebAppMerck.Modelos.Models.Entities.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("IdProvincia");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("WebAppMerck.Modelos.Models.Entities.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });
#pragma warning restore 612, 618
        }
    }
}
